# Trigger builds on commits and merges to branch
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - v24/

# Do not trigger builds on PRs
pr: none

extends:
  template: ../Shared/azure-pipelines.yml